In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/game_data')

In [3]:
df[df.away=='TEN']

,Unnamed: 0,away,away_score,away_stats,home,home_score,home_stats,week,year
0,0,TEN,10,"[18, 320, 234, 86, 5, 28, 2, 5, 223, 42, 1701]",PIT,13,"[18, 320, 234, 86, 5, 28, 2, 5, 223, 42, 1701]",1,2009
43,0,TEN,17,"[17, 286, 159, 127, 3, 15, 4, 7, 303, 30, 1642]",NYJ,24,"[17, 286, 159, 127, 3, 15, 4, 7, 303, 30, 1642]",3,2009
52,0,TEN,17,"[19, 379, 284, 95, 6, 68, 3, 5, 211, 35, 1553]",JAC,37,"[19, 379, 284, 95, 6, 68, 3, 5, 211, 35, 1553]",4,2009
86,0,TEN,0,"[9, 186, -7, 193, 6, 55, 5, 6, 208, 28, 1260]",NE,59,"[9, 186, -7, 193, 6, 55, 5, 6, 208, 28, 1260]",6,2009
126,0,TEN,34,"[14, 315, 163, 152, 8, 58, 0, 5, 217, 44, 1570]",SF,27,"[14, 315, 163, 152, 8, 58, 0, 5, 217, 44, 1570]",9,2009
159,0,TEN,20,"[22, 344, 116, 228, 5, 25, 1, 4, 176, 42, 1939]",HOU,17,"[22, 344, 116, 228, 5, 25, 1, 4, 176, 42, 1939]",11,2009
181,0,TEN,17,"[24, 375, 233, 142, 4, 50, 2, 2, 78, 39, 1979]",IND,27,"[24, 375, 233, 142, 4, 50, 2, 2, 78, 39, 1979]",13,2009
255,0,TEN,17,"[19, 304, 171, 133, 9, 76, 2, 4, 214, 47, 1942]",SEA,13,"[19, 304, 171, 133, 9, 76, 2, 4, 214, 47, 1942]",17,2009
288,0,TEN,29,"[17, 271, 110, 161, 8, 80, 0, 5, 214, 37, 1702]",NYG,10,"[17, 271, 110, 161, 8, 80, 0, 5, 214, 37, 1702]",3,2010
328,0,TEN,34,"[17, 321, 163, 158, 4, 40, 0, 5, 174, 35, 1396]",DAL,27,"[17, 321, 163, 158, 4, 40, 0, 5, 174, 35, 1396]",5,2010
345,0,TEN,30,"[20, 324, 171, 153, 8, 57, 0, 2, 98, 50, 1965]",JAC,3,"[20, 324, 171, 153, 8, 57, 0, 2, 98, 50, 1965]",6,2010
367,0,TEN,25,"[15, 370, 305, 65, 10, 80, 0, 6, 279, 44, 1333]",SD,33,"[15, 370, 305, 65, 10, 80, 0, 6, 279, 44, 1333]",8,2010
387,0,TEN,17,"[15, 259, 124, 135, 5, 55, 3, 5, 209, 38, 1616]",MIA,29,"[15, 259, 124, 135, 5, 55, 3, 5, 209, 38, 1616]",10,2010
421,0,TEN,0,"[9, 162, 138, 24, 10, 79, 3, 7, 328, 44, 1219]",HOU,20,"[9, 162, 138, 24, 10, 79, 3, 7, 328, 44, 1219]",12,2010
485,0,TEN,14,"[16, 270, 213, 57, 9, 74, 2, 8, 352, 37, 1256]",KC,34,"[16, 270, 213, 57, 9, 74, 2, 8, 352, 37, 1256]",16,2010
501,0,TEN,20,"[17, 341, 290, 51, 7, 58, 1, 5, 211, 42, 1877]",IND,23,"[17, 341, 290, 51, 7, 58, 1, 5, 211, 42, 1877]",17,2010
516,0,TEN,14,"[13, 292, 249, 43, 7, 60, 1, 7, 291, 34, 1222]",JAC,16,"[13, 292, 249, 43, 7, 60, 1, 7, 291, 34, 1222]",1,2011
561,0,TEN,31,"[13, 332, 220, 112, 5, 45, 1, 6, 237, 37, 1387]",CLE,13,"[13, 332, 220, 112, 5, 45, 1, 6, 237, 37, 1387]",4,2011
576,0,TEN,17,"[20, 306, 240, 66, 9, 70, 1, 4, 169, 42, 1658]",PIT,38,"[20, 306, 240, 66, 9, 70, 1, 4, 169, 42, 1658]",5,2011
644,0,TEN,30,"[22, 383, 211, 172, 9, 92, 1, 5, 221, 38, 1956]",CAR,3,"[22, 383, 211, 172, 9, 92, 1, 5, 221, 38, 1956]",10,2011
660,0,TEN,17,"[17, 298, 257, 41, 10, 86, 1, 5, 225, 40, 1381]",ATL,23,"[17, 298, 257, 41, 10, 86, 1, 5, 225, 40, 1381]",11,2011
691,0,TEN,23,"[18, 317, 130, 187, 3, 20, 0, 5, 239, 46, 1694]",BUF,17,"[18, 317, 130, 187, 3, 20, 0, 5, 239, 46, 1694]",13,2011
724,0,TEN,13,"[21, 388, 322, 66, 7, 70, 3, 7, 329, 45, 1917]",IND,27,"[21, 388, 322, 66, 7, 70, 3, 7, 329, 45, 1917]",15,2011
756,0,TEN,23,"[17, 361, 275, 86, 6, 47, 1, 6, 286, 46, 1522]",HOU,22,"[17, 361, 275, 86, 6, 47, 1, 6, 286, 46, 1522]",17,2011
796,0,TEN,10,"[9, 212, 174, 38, 8, 59, 1, 7, 361, 49, 981]",SD,38,"[9, 212, 174, 38, 8, 59, 1, 7, 361, 49, 981]",2,2012
818,0,TEN,14,"[17, 325, 167, 158, 7, 73, 3, 7, 326, 42, 1654]",HOU,38,"[17, 325, 167, 158, 7, 73, 3, 7, 326, 42, 1654]",4,2012
836,0,TEN,7,"[18, 267, 215, 52, 10, 75, 2, 6, 256, 43, 1614]",MIN,30,"[18, 267, 215, 52, 10, 75, 2, 6, 256, 43, 1614]",5,2012
867,0,TEN,35,"[21, 390, 193, 197, 3, 25, 0, 3, 124, 35, 1781]",BUF,34,"[21, 390, 193, 197, 3, 25, 0, 3, 124, 35, 1781]",7,2012
903,0,TEN,37,"[17, 293, 116, 177, 4, 39, 0, 4, 208, 48, 1993]",MIA,3,"[17, 293, 116, 177, 4, 39, 0, 4, 208, 48, 1993]",10,2012
934,0,TEN,19,"[20, 360, 250, 110, 6, 42, 2, 4, 201, 49, 1837]",JAC,24,"[20, 360, 250, 110, 6, 42, 2, 4, 201, 49, 1837]",12,2012
...,...,...,...,...,...,...,...,...,...
1111,0,TEN,13,"[13, 223, 157, 66, 7, 44, 2, 4, 140, 31, 1598]",SEA,20,"[13, 223, 157, 66, 7, 44, 2, 4, 140, 31, 1598]",6,2013
1149,0,TEN,28,"[22, 363, 165, 198, 3, 30, 2, 5, 228, 35, 1629]",STL,21,"[22, 363, 165, 198, 3, 30, 2, 5, 228, 35, 1629]",9,2013
1196,0,TEN,23,"[22, 426, 312, 114, 10, 100, 0, 5, 163, 24, 2148]",OAK,19,"[22, 426, 312, 114, 10, 100, 0, 5, 163, 24, 2148]",12,2013
1205,0,TEN,14,"[24, 347, 185, 162, 6, 74, 4, 6, 222, 32, 2035]",IND,22,"[24, 347, 185, 162, 6, 74, 4, 6, 222, 32, 2035]",13,2013
1226,0,TEN,28,"[15, 254, 158, 96, 8, 66, 2, 4, 201, 44, 1240]",DEN,51,"[15, 254, 158, 96, 8, 66, 2, 4, 201, 44, 1240]",14,2013
1252,0,TEN,20,"[22, 346, 164, 182, 1, 4, 1, 3, 140, 39, 2139]",JAC,16,"[22, 346, 164, 182, 1, 4, 1, 3, 140, 39, 2139]",16,2013
1285,0,TEN,26,"[24, 405, 243, 162, 12, 110, 0, 6, 304, 43, 2264]",KC,10,"[24, 405, 243, 162, 12, 110, 0, 6, 304, 43, 2264]",1,2014
1314,0,TEN,7,"[22, 326, 177, 149, 11, 99, 2, 4, 141, 25, 1876]",CIN,33,"[22, 326, 177, 149, 11, 99, 2, 4, 141, 25, 1876]",3,2014
1332,0,TEN,17,"[16, 261, 176, 85, 6, 68, 3, 6, 265, 42, 1059]",IND,41,"[16, 261, 176, 85, 6, 68, 3, 6, 265, 42, 1059]",4,2014
1380,0,TEN,17,"[14, 236, 160, 76, 11, 96, 2, 5, 196, 39, 1856]",WAS,19,"[14, 236, 160, 76, 11, 96, 2, 5, 196, 39, 1856]",7,2014
1415,0,TEN,7,"[14, 210, 143, 67, 9, 67, 2, 8, 414, 49, 1753]",BAL,21,"[14, 210, 143, 67, 9, 67, 2, 8, 414, 49, 1753]",10,2014
1449,0,TEN,24,"[16, 351, 299, 52, 7, 56, 3, 6, 294, 41, 1608]",PHI,43,"[16, 351, 299, 52, 7, 56, 3, 6, 294, 41, 1608]",12,2014
1461,0,TEN,21,"[19, 320, 237, 83, 6, 66, 4, 5, 226, 41, 1604]",HOU,45,"[19, 320, 237, 83, 6, 66, 4, 5, 226, 41, 1604]",13,2014
1504,0,TEN,13,"[19, 357, 262, 95, 7, 47, 0, 5, 203, 34, 2092]",JAC,21,"[19, 357, 262, 95, 7, 47, 0, 5, 203, 34, 2092]",16,2014
1548,0,TEN,42,"[20, 309, 185, 124, 8, 55, 1, 4, 189, 43, 1890]",TB,14,"[20, 309, 185, 124, 8, 55, 1, 4, 189, 43, 1890]",1,2015
1556,0,TEN,14,"[21, 385, 219, 166, 9, 85, 3, 6, 298, 24, 2111]",CLE,28,"[21, 385, 219, 166, 9, 85, 3, 6, 298, 24, 2111]",2,2015
1645,0,TEN,6,"[15, 211, 125, 86, 6, 45, 3, 7, 349, 46, 1868]",HOU,20,"[15, 211, 125, 86, 6, 45, 3, 7, 349, 46, 1868]",8,2015
1659,0,TEN,34,"[25, 483, 371, 112, 9, 66, 1, 5, 253, 46, 1941]",NO,28,"[25, 483, 371, 112, 9, 66, 1, 5, 253, 46, 1941]",9,2015
1682,0,TEN,13,"[22, 316, 212, 104, 6, 59, 1, 5, 226, 30, 1895]",JAC,19,"[22, 316, 212, 104, 6, 59, 1, 5, 226, 30, 1895]",11,2015
1730,0,TEN,8,"[15, 292, 268, 24, 3, 20, 1, 6, 289, 43, 1444]",NYJ,30,"[15, 292, 268, 24, 3, 20, 1, 6, 289, 43, 1444]",14,2015
1751,0,TEN,16,"[15, 282, 223, 59, 3, 29, 3, 5, 272, 47, 1823]",NE,33,"[15, 282, 223, 59, 3, 29, 3, 5, 272, 47, 1823]",15,2015
1781,0,TEN,24,"[14, 231, 94, 137, 6, 60, 1, 6, 300, 47, 1603]",IND,30,"[14, 231, 94, 137, 6, 60, 1, 6, 300, 47, 1603]",17,2015
1811,0,TEN,16,"[22, 363, 224, 139, 12, 83, 1, 3, 142, 40, 1851]",DET,15,"[22, 363, 224, 139, 12, 83, 1, 3, 142, 40, 1851]",2,2016
1845,0,TEN,20,"[16, 320, 196, 124, 11, 93, 1, 5, 257, 31, 1902]",HOU,27,"[16, 320, 196, 124, 11, 93, 1, 5, 257, 31, 1902]",4,2016
1860,0,TEN,30,"[23, 398, 163, 235, 5, 40, 0, 5, 175, 18, 2204]",MIA,17,"[23, 398, 163, 235, 5, 40, 0, 5, 175, 18, 2204]",5,2016
1923,0,TEN,35,"[24, 393, 313, 80, 8, 57, 3, 4, 182, 45, 1411]",SD,43,"[24, 393, 313, 80, 8, 57, 3, 4, 182, 45, 1411]",9,2016
1944,0,TEN,17,"[20, 351, 254, 97, 11, 109, 0, 5, 219, 37, 1861]",IND,24,"[20, 351, 254, 97, 11, 109, 0, 5, 219, 37, 1861]",11,2016
1959,0,TEN,27,"[18, 375, 226, 149, 6, 118, 0, 4, 177, 43, 1765]",CHI,21,"[18, 375, 226, 149, 6, 118, 0, 4, 177, 43, 1765]",12,2016
2007,0,TEN,19,"[21, 389, 241, 148, 2, 25, 3, 4, 143, 35, 1835]",KC,17,"[21, 389, 241, 148, 2, 25, 3, 4, 143, 35, 1835]",15,2016
2022,0,TEN,17,"[19, 263, 205, 58, 6, 49, 1, 7, 313, 43, 1649]",JAX,38,"[19, 263, 205, 58, 6, 49, 1, 7, 313, 43, 1649]",16,2016